<a href="https://colab.research.google.com/github/GzpTez0514/-/blob/main/Pytorch%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A011_%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 定义Dataset的子类
import os
import torch
from torch.utils.data import Dataset
import numpy as np
import pandas as pd
from skimage import io
import torch, torchvision
from torchvision import transforms
import matplotlib.pyplot as plt
import random # 为了plotsamples而导入

# 包含了所有图像的目录，没有具体到某一张图像
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
# 标签文件的目录
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
identity = pd.read_csv(csvpath, sep=' ', header=None)
print(identity.head())

imgdic = os.path.join(imgpath, identity.iloc[0, 0])
print(imgdic)

In [ ]:
# 将读取的标签和图像合并
idx = 0 # 自定义
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
imgdic = os.path.join(imgpath, identity.iloc[index, 0])
iamge = torch.tensor(io.imread(imgdic))
sample = (image, int(identity.iloc[index, 0]))
print(image.shape)
print(sample)
# 成功读取一张图片，并将它和标签打包成一个元组

In [ ]:
# 更换文件拓展名
# identity是个体识别的标签
identity2 = identity.copy()
identity2['2'] = [x[:-3] + 'png' for x in identity2.iloc[:, 0]]
print(identity2.head())
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
imgdic = os.path.join(imgpath, identity2.iloc[idx, 2])
image = torch.tensor(io.imread(imgdic))
sample = (image, int(identity.iloc[idx, 1]))

In [ ]:
# 包装成类
from torch.utils.data import Dataset
import numpy as np
import pandas as pd
from skimage import io
import torch, torchvision
from torchvision import transforms
import matplotlib.pyplot as plt
import random 

class CustomDataset(Dataset):
  '''
  自定义数据集，用于读取celebA数据集中的个体识别数据的标签和图像
  图像的格式为jpg
  '''
  def __init__(self, csv_file, root_dir, transform=None):
    '''
    参数说明：
      csv_file:标签的具体位置
      root_dir：所有图片所在的根目录
      transform：选填，需要对样本进行预处理
    '''
    super().__init__()
    self.identity = pd.read_csv(csv_file, sep=' ', header=None)
    self.root_dir = root_dir
    self.transform = transform
  
  def __len__(self):
    # 展示数据总共有多少个样本
    return len(self.identity)

  def __info__(self):
    print('CustomData')
    print(f'\t Number of samples: {len(self.identity)}')
    print(f'\t Number of classes: {len(np.unique(self.identity.iloc[:, 1]))}')
    print(f'\t root_dir: {self.root_dir}')

  def __getitem__(self, idx):
    # 保证idx不是一个tensor
    if torch.is_tensor(idx):
      idx = idx.tolist()

    # 图像目录
    imgdic = os.path.join(self.root, self.identity.iloc[idex, 0])
    # 提取出的，索引为idx的图像的像素值矩阵
    image = io.imread(imgdic)
    label = self.identity.iloc[idex, 1]

    if self.transform != None:
      image = self.transform(image)

    sample = (image, label)
    return sample

img_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csv_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'

data = CustomDataset(root_dir=img_path, 
           csv_file=csv_path, 
           transform=transforms.Totensor())

print(data.__info__())
print(__len__())

for x,y in data:
  print(x.shape, y)
  break

# getitem的存在令子类生成的数据能够被索引调用和查看
data[998]

# 让每个数据集随机显示5张图片
plotsample(data)

# 用来分割训练集和测试集的工具
from torch.utils.data import random_split
print(data.__len__())

train, test = random_split(data, [700, 300], generator=torch.Generator().manual_seed(42))
print(train.__len__()) # 分割数据集由Dataset变成了Subset, 继承自Dataset类的方法会全保留，而自己设置的方法则会失效
print(train.__info__())
print(test.__len__()

In [ ]:
# 读取标签属性，并放置到类CustomDataset_attr中
class CustomDataset_attr(Dataset):
  '''
  自定义数据集，用于读取celeBA数据集中的属性识别数据的标签和图像
  图像格式为jpg
  '''
  def __init__(self, csv_file, root_dir, labelname, transform=None):
    '''
    参数说明：
      csv_file:标签的具体地址
      root_dir:所有图片所在的根目录
      transform:选填，需要对样本进行的预处理
    '''
    super().__init__()
    self.attr_ = pd.read_csv(csv_path, header=None)
    self.root_dir = root_dir
    self.labelname = labelname
    self.transform = transform

  def __len__(self):
    # 展示数据中总共有多少个样本
    return len(self.attr_)

  def __info__(self):
    print('CustomData')
    print(f'\t Number of samples: {len(self.sttr_) - 1}')
    print(f'\t root_dir: {self.root_dir}')

  def __getitem__(self, idx):
    # 保证idx不是一个tensor
    if torch.is_tensor(idx):
      idx = idx.tolist()
    
    self.attr_ = pd.DataFrame(self.attr_.iloc[1:, 0].str.split().tolist(),
                  columns=self.attr_.iloc[0, 0].split())
    
    imgdic = os.path.join(self.root_dir, self.attr_.iloc[idx, 0]) # 图像目录
    image = io.imread(imgdic) # 提取出的，索引为idx的图像的像素值矩阵
    label = int(self.attr_.loc[idx, self.labelname])

    if self.transform != None:
      image = self.transform(image)
    
    sample = (image, label)
    return sample

imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csv_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
labelname = 'Attractive'

data = CustomDataset_attr(csv_path, img_path, labelname)
print(data)
print(data.__info__())
print(data[500])

In [ ]:
# 从二维表到四维tensor
# csv
import pandas as pd
data = pd.read_csv(r'........')

# txt
data = pd.read_csv(r'........', sep=' ')

# 导入数据之后，将二维表格整理成更高维的数据，就可以放入卷积网络进行训练
import numpy as np
import torch
import matplotlib.pyplot as plt

data = np.random.randint(0, 255, (10, 10000)) # 假设现在是10个样本，每个样本10000个特征
data.reshape(10, 1, 100, 100) # 可以直接使用reshape的方式将数据调整为4维
data = torch.tensor(data) # 再放入tensor中转换格式
plt.imshow(data.view(-1, 100, 100, 1)[0])
print(data)

In [ ]:
# 多项式升维
from sklearn.preprocessing import PolynomialFeatures as PF
import numpy as np

# 如果数据是一维的
x = np.arange(1, 4).reshape(-1, 1)
print(x)

# 二次多项式，参数degree控制多项式的次方
poly = PF(degree=2)

# 接口transform直接调用
x_ = poly.fit_transform(x)
print(x_)

# 三次多项式
PF(degree=3).fit_transform(x)


In [ ]:
# 从mat/pt/Imdb到四维tensor
# FashionMNIST数据集就是pt格式的数据,可以直接使用torch.load进行读取
import torch
x, y = torch.load(r'-------------')
print(x.shape)
print(y)

In [ ]:
# 图片数据的预处理与数据增强
# 1、数据预处理
import torch
import torchvision
from torchvision import transforms
from torch import nn

transform = transform.Compose([transforms.Resize(256), transforms.CenterCrop(224)])
# 等价于
transform = nn.Sequential(transforms.Resize(256), transforms.CenterCrop(224))

# 归一化，归一化之前，通道上的全部像素值都必须要被转成Tensor
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(0.5, 0.5)])

# 在实际执行代码时，我们往往将数据增强和数据预处理的代码写在一起
transform = transforms.Compose([transforms.Resize(256), # 先对尺寸进行操作
                 transforms.RandomCrop(size=(224))，
                 transforms.RandomHorizontalFlip(p=1)， # 再进行翻转和旋转

                 transforms.RandomRotation(degrees=(-70, 70)),
                 transforms.ToTensor()
                 transforms.Normalize(0.5, 0.5))                
                 ])

In [4]:
# 优化算法 Adagrad
import numpy as np
# 假设现在有4个权重，迭代了3次
# 第一次迭代时全部的梯度
gt1 = np.array([[1],
         [2],
         [3],
         [4]])

# 第二次迭代时全部的梯度
gt2 = np.array([[4],
         [5],
         [6],
         [7]])

# 第三次迭代时全部的梯度
gt3 = np.array([[7],
         [8],
         [9],
         [10]])

# 第一次迭代时gt1与自己的转置相乘得到的外积
print(gt1 * gt1.T)

# t次迭代及之前，所有的gt与自己的转置相乘得到的外积
Gt = (gt1 * gt1.T) + (gt2 * gt2.T) + (gt3 * gt3.T)
print(Gt)
print(np.diag(np.diagonal(Gt))) # 取对角矩阵

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[ 66  78  90 102]
 [ 78  93 108 123]
 [ 90 108 126 144]
 [102 123 144 165]]
[[ 66   0   0   0]
 [  0  93   0   0]
 [  0   0 126   0]
 [  0   0   0 165]]
