<a href="https://colab.research.google.com/github/GzpTez0514/-/blob/main/Pytorch%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0_%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.arange(12)
print(x)
print(x.shape)
# 张量中元素的个数
print(x.numel())
X = x.reshape(3, 4)
print(X)

# 形状为（2， 3， 4）的张量，元素全为0
a = torch.zeros((2, 3, 4))
print(a)

# 形状为(2, 3, 4)的张量，元素全为1
b = torch.ones((2, 3, 4))
print(b)

# 形状为(3, 4)的张量，每个元素都从均值为0、标准差为1的正态分布中随机采样
c = torch.randn(3, 4)
print(c)

# 最外层的列表对应于轴0，内层的列表对应于轴1
d = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(d)

In [14]:
# 运算符
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
# 指数运算
print(torch.exp(x))



tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
