<a href="https://colab.research.google.com/github/GzpTez0514/-/blob/main/Pytorch%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0_3%E3%80%81%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 标量
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
print(x + y)
print(x * y)
print(x / y)
print(x ** y)

tensor(5.)
tensor(6.)
tensor(1.5000)
tensor(9.)


In [4]:
# 向量
x = torch.arange(4)
print(x)
print(x[3])

tensor([0, 1, 2, 3])
tensor(3)


In [6]:
# 长度、维度和形状
x = torch.arange(4)  
print(len(x))   # 张量的长度
print(x.shape)  # 张量的形状和维度

4
torch.Size([4])


In [10]:
# 矩阵
A = torch.arange(20).reshape(5, 4)
print(A)
print(A.T)  # A的转置

B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)
print(B == B.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
# 张量
X = torch.arange(24).reshape(2, 3, 4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [14]:
# 张量算法的基本性质
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(A)
print(A + B)
print(A * B)

a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(a + X)
print((a * X).shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


In [24]:
# 降维
x = torch.arange(4, dtype=torch.float32)
print(x)
print(x.sum())

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
print(A.sum())
print(A.shape)

A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0)
print(A_sum_axis0.shape)

A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1)
print(A_sum_axis1.shape)

A_sum_axis01 = A.sum(axis=[0, 1])  # 相当于对所有元素求和
print(A_sum_axis01)
print(A_sum_axis01.shape)

print(A.mean(axis=0))
print(A.sum(axis=0) / A.shape[0])


tensor([0., 1., 2., 3.])
tensor(6.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(190.)
torch.Size([5, 4])
tensor([40., 45., 50., 55.])
torch.Size([4])
tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])
tensor(190.)
torch.Size([])
tensor([ 8.,  9., 10., 11.])
tensor([ 8.,  9., 10., 11.])


In [29]:
# 非降维求和 
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
sum_A = A.sum(axis=1, keepdims=True)  # 求和之后不改变维数
print(sum_A)
print(sum_A.shape)

# 由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A
print(A / sum_A)

# 如果我们想沿某个轴计算A元素的累积总和，比如axis=0（按行计算），我们可以调用cumsum函数,此函数不会沿任何轴降低输入张量的维度
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [31]:
# 点积
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x, y))  # 向量与向量相乘

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)


In [33]:
# 矩阵-向量积
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
print(A.shape)
print(x.shape)
print(torch.mv(A, x))  # 矩阵与向量相乘

B = torch.ones(4, 3)
print(torch.mm(A, B))  # 矩阵与矩阵相乘

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [36]:
# 范数
u = torch.tensor([3.0, -4.0])
res1 = torch.norm(u)  # 计算向量的L2范数
print(res1)

res2 = torch.abs(u).sum()  # 计算向量的L1范数
print(res2)

res3 = torch.norm(torch.ones((4, 9)))  # 计算F范数:就是求矩阵元素平方和的平方根
print(res3)

tensor(5.)
tensor(7.)
tensor(6.)
