<a href="https://colab.research.google.com/github/GzpTez0514/-/blob/main/Pytorch%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0_1%E3%80%81%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
x = torch.arange(12)
print(x)
print(x.shape)
# 张量中元素的个数
print(x.numel())
X = x.reshape(3, 4)
print(X)

# 形状为（2， 3， 4）的张量，元素全为0
a = torch.zeros((2, 3, 4))
print(a)

# 形状为(2, 3, 4)的张量，元素全为1
b = torch.ones((2, 3, 4))
print(b)

# 形状为(3, 4)的张量，每个元素都从均值为0、标准差为1的正态分布中随机采样
c = torch.randn(3, 4)
print(c)

# 最外层的列表对应于轴0，内层的列表对应于轴1
d = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(d)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[ 0.6410,  0.9443, -0.6827, -1.1563],
        [ 0.3870,  0.3132, -1.0187, -2.1897],
        [ 0.6069, -0.4766, -0.1479, -1.5970]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [10]:
import torch
# 运算符
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
# 指数运算
print(torch.exp(x))

# 对张量进行纵向和横向合并
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], 
          [1, 2, 3, 4],
          [4, 3, 2, 1]])

print(torch.cat((X, Y), axis=0))
print(torch.cat((X, Y), dim=0))
print(torch.cat((X, Y), axis=1))
print(X == Y)
# 对张量中所有的元素求和
print(X.sum())  # tensor(66.)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [11]:
# 广播机制
import torch
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a)
print(b)
# 将两个矩阵广播为一个更大的3*2矩阵,矩阵a将复制列，矩阵b将复制行，然后再按元素相加
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [12]:
# 索引和切片
import torch
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4 ,3],
          [1, 2, 3, 4], 
          [4, 3, 2, 1]])
print(X)
print(Y)
# 用[-1]选择最后一个元素
print(X[-1])
# 用[1:3]选择第二个和第三个元素
print(X[1:3])
X[1, 2] = 9
print(X)
X[0:2, :] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [13]:
# 节省内存
import torch
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3],
          [1, 2, 3, 4],
          [4, 3, 2, 1]])

# 如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。
before = id(Y)
print(before)  # 140439963779152
Y = Y + X
print(id(Y))  # 140439963779920

# 原地执行这些更新,不分配新的内存
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))  # 140439963626672
Z[:] = X + Y
print('id(Z):', id(Z))  # 140439963626672

140221790737904
140221790738384
id(Z): 140221790737904
id(Z): 140221790737904


In [14]:
from typing_extensions import TypeAlias
# 转换为其他Python对象
import torch
import numpy as np
A = X.numpy()
B = torch.tensor(A)
print(type(A))
print(type(B))

a = torch.tensor([3.5])
print(a)
print(a.item())
print(float(a))
print(int(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([3.5000])
3.5
3.5
3


In [5]:
# 一维张量索引
import torch
t1 = torch.arange(1, 11)
print(t1)
print(t1[1: 8: 2])
print(t1[1: : 2])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([2, 4, 6, 8])
tensor([ 2,  4,  6,  8, 10])


In [17]:
# 二维张量索引
t2 = torch.arange(1, 10).reshape(3, 3)
print(t2)
print(t2[0, 1])
print(t2[0, ::2])
print(t2[0, [0, 2]])
print(t2[::2, ::2])
print(t2[[0, 2], 1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(2)
tensor([1, 3])
tensor([1, 3])
tensor([[1, 3],
        [7, 9]])
tensor([2, 8])


In [24]:
# 三维张量的索引
t3 = torch.arange(1, 28).reshape(3, 3, 3)
print(t3)
print(t3[1, 1, 1])
print(t3[1, ::2, ::2])
print(t3[::2, ::2, ::2])
print(t3.shape)
print(t3[1, 1, 1])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
tensor(14)
tensor([[10, 12],
        [16, 18]])
tensor([[[ 1,  3],
         [ 7,  9]],

        [[19, 21],
         [25, 27]]])
torch.Size([3, 3, 3])
tensor(14)


In [29]:
# 张量的函数索引
t1 = torch.arange(1, 11)
print(t1)
indices = torch.tensor([1, 2])
print(indices)
print(torch.index_select(t1, 0, indices))

t2 = torch.arange(12).reshape(4, 3)
print(t2)
print(torch.index_select(t2, 1, indices))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([1, 2])
tensor([2, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])


In [15]:
import torch
# 不同维度的张量计算过程中广播 首先将低维的张量升
t2 = torch.zeros((3, 4))
print(t2)

t3 = torch.zeros(3, 4, 5)
print(t3)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [32]:
t2 = torch.arange(4).reshape(2, 2)
print(t2)
print(t2.ndim)

# 转化为3维张量
t2 = t2.reshape(1, 2, 2)
print(t2)

# 转化为4维张量
t2 = t2.reshape(1, 1, 2, 2)
print(t2)

t3 = torch.zeros(3, 2, 2)
print(t3)
print(t2 + t3)

tensor([[0, 1],
        [2, 3]])
2
tensor([[[0, 1],
         [2, 3]]])
tensor([[[[0, 1],
          [2, 3]]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[[0., 1.],
          [2., 3.]],

         [[0., 1.],
          [2., 3.]],

         [[0., 1.],
          [2., 3.]]]])


In [37]:
# 逐点计算
t1 = torch.tensor([1, 2])
print(t1)

t2 = torch.tensor([3, 4])
print(t2)
print(torch.add(t1, t2))
print(t1 + t2)
print(t1 / t2)

tensor([1, 2])
tensor([3, 4])
tensor([4, 6])
tensor([4, 6])
tensor([0.3333, 0.5000])


In [41]:
# Tensor数值调整函数
t = torch.randn(5)
print(t)
print(torch.round(t))  # 四舍五入
print(torch.abs(t))
print(torch.neg(t))  # 取反

tensor([-1.6453,  0.8934,  0.1217,  0.4126, -1.2541])
tensor([-2.,  1.,  0.,  0., -1.])
tensor([1.6453, 0.8934, 0.1217, 0.4126, 1.2541])
tensor([ 1.6453, -0.8934, -0.1217, -0.4126,  1.2541])


In [64]:
# tensor常用科学计算
print(torch.pow(torch.tensor(2), 2)) # 计算2的2次幂


# 需要注意的是，虽然Python是动态编译的编程语言，但在PyTorch中，由于
# 会涉及GPU计算，因此很多时候元素类型不会在实际执行函数计算时进行调整。此处的科学运算大多数都要求对象类型是浮点型，我们需要提前进行类型转化。
t = torch.arange(1, 4).float()
print(t)  # tensor([1., 2., 3.])
print(torch.exp(t)) # e^t
print(torch.exp2(t)) # 2^t
print(torch.expm1(t)) # e^(t-1)
print(torch.pow(t, 2)) # t^2 tensor([1., 4., 9.])
print(torch.square(t)) # t^2 tensor([1., 4., 9.])
print(torch.sqrt(t)) # t^0.5
print(torch.pow(t, 0.5)) # t^0.5
print(torch.log10(t))
print(torch.log(t))
print(torch.log2(t)) 
print(torch.log1p(t)) # log(t-1)
print(torch.exp(torch.log(t)))  # tensor([1., 2., 3.])
print(torch.exp2(torch.log2(t))) # tensor([1., 2., 3.])
print(torch.expm1(torch.log1p(t))) # tensor([1., 2., 3.]


tensor(4)
tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([2., 4., 8.])
tensor([ 1.7183,  6.3891, 19.0855])
tensor([1., 4., 9.])
tensor([1., 4., 9.])
tensor([1.0000, 1.4142, 1.7321])
tensor([1.0000, 1.4142, 1.7321])
tensor([0.0000, 0.3010, 0.4771])
tensor([0.0000, 0.6931, 1.0986])
tensor([0.0000, 1.0000, 1.5850])
tensor([0.6931, 1.0986, 1.3863])
tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1., 2., 3.])
