<a href="https://colab.research.google.com/github/GzpTez0514/-/blob/main/Pytorch%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A011_%E5%9B%BE%E5%83%8F%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 定义Dataset的子类
import os
import torch
from torch.utils.data import Dataset
import numpy as np
import pandas as pd
from skimage import io
import torch, torchvision
from torchvision import transforms
import matplotlib.pyplot as plt
import random # 为了plotsamples而导入

# 包含了所有图像的目录，没有具体到某一张图像
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
# 标签文件的目录
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
identity = pd.read_csv(csvpath, sep=' ', header=None)
print(identity.head())

imgdic = os.path.join(imgpath, identity.iloc[0, 0])
print(imgdic)

In [ ]:
# 将读取的标签和图像合并
idx = 0 # 自定义
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
imgdic = os.path.join(imgpath, identity.iloc[index, 0])
iamge = torch.tensor(io.imread(imgdic))
sample = (image, int(identity.iloc[index, 0]))
print(image.shape)
print(sample)
# 成功读取一张图片，并将它和标签打包成一个元组

In [ ]:
# 更换文件拓展名
# identity是个体识别的标签
identity2 = identity.copy()
identity2['2'] = [x[:-3] + 'png' for x in identity2.iloc[:, 0]]
print(identity2.head())
imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csvpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
imgdic = os.path.join(imgpath, identity2.iloc[idx, 2])
image = torch.tensor(io.imread(imgdic))
sample = (image, int(identity.iloc[idx, 1]))

In [ ]:
# 包装成类
from torch.utils.data import Dataset
import numpy as np
import pandas as pd
from skimage import io
import torch, torchvision
from torchvision import transforms
import matplotlib.pyplot as plt
import random 

class CustomDataset(Dataset):
  '''
  自定义数据集，用于读取celebA数据集中的个体识别数据的标签和图像
  图像的格式为jpg
  '''
  def __init__(self, csv_file, root_dir, transform=None):
    '''
    参数说明：
      csv_file:标签的具体位置
      root_dir：所有图片所在的根目录
      transform：选填，需要对样本进行预处理
    '''
    super().__init__()
    self.identity = pd.read_csv(csv_file, sep=' ', header=None)
    self.root_dir = root_dir
    self.transform = transform
  
  def __len__(self):
    # 展示数据总共有多少个样本
    return len(self.identity)

  def __info__(self):
    print('CustomData')
    print(f'\t Number of samples: {len(self.identity)}')
    print(f'\t Number of classes: {len(np.unique(self.identity.iloc[:, 1]))}')
    print(f'\t root_dir: {self.root_dir}')

  def __getitem__(self, idx):
    # 保证idx不是一个tensor
    if torch.is_tensor(idx):
      idx = idx.tolist()

    # 图像目录
    imgdic = os.path.join(self.root, self.identity.iloc[idex, 0])
    # 提取出的，索引为idx的图像的像素值矩阵
    image = io.imread(imgdic)
    label = self.identity.iloc[idex, 1]

    if self.transform != None:
      image = self.transform(image)

    sample = (image, label)
    return sample

img_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csv_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'

data = CustomDataset(root_dir=img_path, 
           csv_file=csv_path, 
           transform=transforms.Totensor())

print(data.__info__())
print(__len__())

for x,y in data:
  print(x.shape, y)
  break

# getitem的存在令子类生成的数据能够被索引调用和查看
data[998]

# 让每个数据集随机显示5张图片
plotsample(data)

# 用来分割训练集和测试集的工具
from torch.utils.data import random_split
print(data.__len__())

train, test = random_split(data, [700, 300], generator=torch.Generator().manual_seed(42))
print(train.__len__()) # 分割数据集由Dataset变成了Subset, 继承自Dataset类的方法会全保留，而自己设置的方法则会失效
print(train.__info__())
print(test.__len__()

In [ ]:
# 读取标签属性，并放置到类CustomDataset_attr中
class CustomDataset_attr(Dataset):
  '''
  自定义数据集，用于读取celeBA数据集中的属性识别数据的标签和图像
  图像格式为jpg
  '''
  def __init__(self, csv_file, root_dir, labelname, transform=None):
    '''
    参数说明：
      csv_file:标签的具体地址
      root_dir:所有图片所在的根目录
      transform:选填，需要对样本进行的预处理
    '''
    super().__init__()
    self.attr_ = pd.read_csv(csv_path, header=None)
    self.root_dir = root_dir
    self.labelname = labelname
    self.transform = transform

  def __len__(self):
    # 展示数据中总共有多少个样本
    return len(self.attr_)

  def __info__(self):
    print('CustomData')
    print(f'\t Number of samples: {len(self.sttr_) - 1}')
    print(f'\t root_dir: {self.root_dir}')

  def __getitem__(self, idx):
    # 保证idx不是一个tensor
    if torch.is_tensor(idx):
      idx = idx.tolist()
    
    self.attr_ = pd.DataFrame(self.attr_.iloc[1:, 0].str.split().tolist(),
                  columns=self.attr_.iloc[0, 0].split())
    
    imgdic = os.path.join(self.root_dir, self.attr_.iloc[idx, 0]) # 图像目录
    image = io.imread(imgdic) # 提取出的，索引为idx的图像的像素值矩阵
    label = int(self.attr_.loc[idx, self.labelname])

    if self.transform != None:
      image = self.transform(image)
    
    sample = (image, label)
    return sample

imgpath = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Img\Img_celeba.7z\img_celeba'
csv_path = r'C:\学习资料文件夹\深兰资料\数据&论文\WEEK10-WEEK14-CV数据包\datasets4\picturestotensor\celebAsubset\Anno\identity_CelebA_1000.txt'
labelname = 'Attractive'

data = CustomDataset_attr(csv_path, img_path, labelname)
print(data)
print(data.__info__())
print(data[500])

In [ ]:
# 从二维表到四维tensor
# csv
import pandas as pd
data = pd.read_csv(r'........')

# txt
data = pd.read_csv(r'........', sep=' ')

# 导入数据之后，将二维表格整理成更高维的数据，就可以放入卷积网络进行训练
import numpy as np
import torch
import matplotlib.pyplot as plt

data = np.random.randint(0, 255, (10, 10000)) # 假设现在是10个样本，每个样本10000个特征
data.reshape(10, 1, 100, 100) # 可以直接使用reshape的方式将数据调整为4维
data = torch.tensor(data) # 再放入tensor中转换格式
plt.imshow(data.view(-1, 100, 100, 1)[0])
print(data)

In [ ]:
# 多项式升维
from sklearn.preprocessing import PolynomialFeatures as PF
import numpy as np

# 如果数据是一维的
x = np.arange(1, 4).reshape(-1, 1)
print(x)

# 二次多项式，参数degree控制多项式的次方
poly = PF(degree=2)

# 接口transform直接调用
x_ = poly.fit_transform(x)
print(x_)

# 三次多项式
PF(degree=3).fit_transform(x)


In [ ]:
# 从mat/pt/Imdb到四维tensor
# FashionMNIST数据集就是pt格式的数据,可以直接使用torch.load进行读取
import torch
x, y = torch.load(r'-------------')
print(x.shape)
print(y)

In [ ]:
# 图片数据的预处理与数据增强
# 1、数据预处理
import torch
import torchvision
from torchvision import transforms
from torch import nn

transform = transform.Compose([transforms.Resize(256), transforms.CenterCrop(224)])
# 等价于
transform = nn.Sequential(transforms.Resize(256), transforms.CenterCrop(224))

# 归一化，归一化之前，通道上的全部像素值都必须要被转成Tensor
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(0.5, 0.5)])

# 在实际执行代码时，我们往往将数据增强和数据预处理的代码写在一起
transform = transforms.Compose([transforms.Resize(256), # 先对尺寸进行操作
                 transforms.RandomCrop(size=(224))，
                 transforms.RandomHorizontalFlip(p=1)， # 再进行翻转和旋转

                 transforms.RandomRotation(degrees=(-70, 70)),
                 transforms.ToTensor()
                 transforms.Normalize(0.5, 0.5))                
                 ])

In [4]:
# 优化算法 Adagrad
import numpy as np
# 假设现在有4个权重，迭代了3次
# 第一次迭代时全部的梯度
gt1 = np.array([[1],
         [2],
         [3],
         [4]])

# 第二次迭代时全部的梯度
gt2 = np.array([[4],
         [5],
         [6],
         [7]])

# 第三次迭代时全部的梯度
gt3 = np.array([[7],
         [8],
         [9],
         [10]])

# 第一次迭代时gt1与自己的转置相乘得到的外积
print(gt1 * gt1.T)

# t次迭代及之前，所有的gt与自己的转置相乘得到的外积
Gt = (gt1 * gt1.T) + (gt2 * gt2.T) + (gt3 * gt3.T)
print(Gt)
print(np.diag(np.diagonal(Gt))) # 取对角矩阵

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[ 66  78  90 102]
 [ 78  93 108 123]
 [ 90 108 126 144]
 [102 123 144 165]]
[[ 66   0   0   0]
 [  0  93   0   0]
 [  0   0 126   0]
 [  0   0   0 165]]


In [7]:
# 调用经典架构
import torch
import torch.nn as nn
from torchvision import models as m

print(dir(m)) # 查看models里面的类
m.AlexNet() # 查看需要填写的参数是什么
m.alexnet() # 将AlexNet父类的功能包含在里面，不允许对原始架构进行参数输入，但是可以进行预训练
m.resnet18()

# 在实际使用模型时，我们几乎总是直接调用小的类来进行使用
# 查看每个类中的结构
resnet18_ = m.resnet18()
vgg16_ = m.vgg16()

# 带有名称的，可以直接用.名称的方式进行调用。通常最外层都是具有名称的，可以直接像调用属性一样调用
print(resnet18_.conv1)
print(resnet18_.layer1)

# 不带名称的，而前面有数字编号的，则只能使用数字编号进行调用
print(resnet18_)
print(resnet18_.layer1[0]) # 调用layer1层的BasicBlock
print(resnet18_.layer1[0].conv1)

print(vgg16_)
print(vgg16_.features[0])

['AlexNet', 'ConvNeXt', 'DenseNet', 'EfficientNet', 'GoogLeNet', 'GoogLeNetOutputs', 'Inception3', 'InceptionOutputs', 'MNASNet', 'MobileNetV2', 'MobileNetV3', 'RegNet', 'ResNet', 'ShuffleNetV2', 'SqueezeNet', 'VGG', 'VisionTransformer', '_GoogLeNetOutputs', '_InceptionOutputs', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_utils', 'alexnet', 'convnext', 'convnext_base', 'convnext_large', 'convnext_small', 'convnext_tiny', 'densenet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'detection', 'efficientnet', 'efficientnet_b0', 'efficientnet_b1', 'efficientnet_b2', 'efficientnet_b3', 'efficientnet_b4', 'efficientnet_b5', 'efficientnet_b6', 'efficientnet_b7', 'feature_extraction', 'googlenet', 'inception', 'inception_v3', 'mnasnet', 'mnasnet0_5', 'mnasnet0_75', 'mnasnet1_0', 'mnasnet1_3', 'mobilenet', 'mobilenet_v2', 'mobilenet_v3_large', 'mobilenet_v3_small', 'mobilenetv2', 'mobilenetv3', 'optical_fl

In [9]:
# 我们可以根据我们自己的需要修改部分层的超参数
# 所有的类都是基于ImageNet数据集构建，因此输入通道数都为3，输出的类别都为1000
# 当我们更换自己的数据集的时候，就需要对输入和输出进行变化
in_channels = 1
out_num = 10
print(resnet18_)

# 需要替换掉整个层
resnet18_.conv1 = nn.Conv2d(in_channels, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
resnet18_.fc = nn.Linear(in_features=512, out_features=out_num, bias=False)
print(resnet18_)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [10]:
# 基于经典架构自建架构
# VGG + 残差单元
!pip install torchinfo
import torch
from torch import nn
from torchvision import models as m
from torchinfo import summary

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
# 先查看网络结构，挑选我们要使用的部分
vgg16_bn_ = m.vgg16_bn() # 初始化的参数
print(vgg16_bn_)

resnet18_ = m.resnet18()
print(resnet18_)

class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    # 第一个卷积层自己写，以保证输入数据在尺寸、通道数上都正确
    self.block1 = nn.Sequential(nn.Conv2d(1, 64, kernel_size=3, stride=1, padding=1),
                  vgg16_bn_.features[1:3])
    
    # 后续的架构直接从经典架构中选
    # 对尺寸很小的数据集而言，我们的深度根本就不深，因此可以试着在特征图数量上有所增加
    self.block2 = vgg16_bn_.features[7:14]
    self.block3 = resnet18_.layer3
    # 自适应平均池化+线性层，此处都与残差网络一致
    self.avgpool = resnet18_.avgpool
    # 输出的线性层自己写，以确保输出的类别数量正确
    self.fc = nn.Linear(in_features=256, out_features=10, bias=True)

  def forward(self, x):
    x = self.block1(x)
    x = self.block3(self.block2(x))
    x = x.view(-1, 256)
    x = self.fc(x)

data = torch.ones(10, 1, 28, 28)
net = MyNet()
net(data)

# 查看自己构建的网络和参数量
summary(net, input_size=(10, 1, 28, 28), depth=1, device='cpu')


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256

Layer (type:depth-idx)                   Output Shape              Param #
MyNet                                    --                        --
├─Sequential: 1-1                        [10, 64, 28, 28]          768
├─Sequential: 1-2                        [10, 128, 14, 14]         221,952
├─Sequential: 1-3                        [10, 256, 7, 7]           2,099,712
├─Linear: 1-4                            [490, 10]                 2,570
Total params: 2,325,002
Trainable params: 2,325,002
Non-trainable params: 0
Total mult-adds (G): 2.77
Input size (MB): 0.03
Forward/backward pass size (MB): 50.22
Params size (MB): 9.30
Estimated Total Size (MB): 59.55

In [38]:
from torchvision.models.resnet import resnet18
# 实现预训练
import torch
import torch.nn as nn
from torchvision import models as m

resnet18_ = m.resnet18()
#print(resnet18_)

rs18pt = m.resnet18(pretrained=True) 
print(resnet18_.conv1.weight[0]) # 初始化的参数，准备好训练
print(rs18pt.conv1.weight[0]) # 经过预训练的参数

# 属性requires_grad为true，意味着可以参与反向传播
# 预训练的参数刚被导入时，都是默认可以被训练的
rs18pt.conv1.weight[0].requires_grad # True

# 将导入的预训练模型中所有的参数锁住
for param in rs18pt.parameters():
  param.requires_grad = False

rs18pt.conv1.weight[0].requires_grad # False

# 使用新的层覆盖原来的层
rs18pt.conv1 = nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
# 新生成的层默认requires_grad=True
# 因此在锁定模型中的参数后，只要覆盖掉原来的层，或者在原来的层之后加上新的层，新的层默认就是可以训练的
# 但是新的层将会覆盖掉原来层已经训练好的参数，所以我们一般不对conv1进行覆盖
rs18pt.conv1.weight.requires_grad # True


# 按照这一逻辑定义架构
# 让18层残差网络的前2个layers都被冻结，后面两个layers从0开始训练
resnet18_ = m.resnet18()
rs18pt = m.resnet18(pretrained=True)
fcin = rs18pt.fc.in_features

for param in rs18pt.parameters():
  param.requires_grad = False

class MyNet_pretrained(nn.Module):
  def __init__(self):
    super().__init__()
    # 迁移层（锁住）
    self.pretrained_ = nn.Sequential(rs18pt.conv1,
                     rs18pt.bn1,
                     rs18pt.relu,
                     rs18pt.maxpool,
                     rs18pt.layer1,
                     rs18pt.layer2)
    # 允许训练的层
    self.train_ = nn.Sequential(resnet18_.layer3,
                   resnet18_.layer4,
                   resnet18_.avgpool)
    
    # 输出的线性层自己写，以确保输出的类别数量正确
    self.fc = nn.Linear(in_features=fcin, out_features=10, bias=True)

  def forward(self, x):
    x = self.pretrained(x)
    x = self.train_(x)
    x = x.view(-1, 512)
    x = self.fc(x)
  
net = MyNet_pretrained()
print(net.pretrained_)
print(net.train_)
print(net.pretrained_[0].weight.requires_grad) # False
print(net.train_[0][0].conv1.weight.requires_grad) # True

tensor([[[ 8.7647e-03,  1.9748e-02, -1.0925e-03, -4.2401e-03,  2.6497e-02,
          -2.9407e-02,  1.2824e-02],
         [ 3.0578e-03, -4.7486e-02,  2.3529e-02,  3.2250e-04,  7.0533e-03,
           5.1749e-03, -8.7045e-03],
         [ 2.9702e-03,  1.8962e-02, -2.2133e-02, -2.8205e-02,  1.5407e-02,
          -2.7863e-03, -1.8765e-02],
         [ 1.0422e-02, -8.7624e-03,  3.7211e-02, -7.0412e-03,  2.0084e-02,
          -2.8198e-02, -2.6693e-02],
         [-3.4844e-02, -2.1606e-02, -6.8359e-02, -3.3809e-04,  2.6320e-02,
          -6.6771e-03,  3.2061e-02],
         [ 6.2157e-03, -8.2307e-03,  2.0330e-02, -3.8204e-03, -5.0498e-02,
           6.4256e-03, -3.6002e-02],
         [ 5.3977e-02,  7.9113e-03, -3.8774e-02,  3.2602e-02,  2.4778e-03,
          -1.0423e-02, -1.6586e-03]],

        [[ 2.5950e-03, -1.7084e-02,  5.8692e-02, -7.0571e-03,  2.6684e-02,
          -2.4464e-02,  2.1102e-02],
         [ 6.7129e-03, -1.4151e-02, -8.6404e-03, -4.2838e-03,  2.8683e-02,
          -1.8892e-02,  3.5